repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: forge-fmt
        name: Forge Formatter
        entry: forge fmt
        language: system
        types: [file]
        pass_filenames: false
      - id: hex-private-key-detector
        name: Hex Private Key Detector
        entry: sh -c '! grep -E "=[0-9a-fA-F]{64}" $@'
        language: system
        require_serial: true
